name: Checkmarx AST Scan
on:
  push:
    branches:      
      - master
      - main    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkmarx AST CLI Action
        uses: checkmarxDev/ast-github-action@main #Github Action version
        with:
         project_name: DVNA_GithubAction
         cx_tenant: yalin_demo
         base_uri: https://eu.ast.checkmarx.net
         cx_client_id: ${{ secrets.CLIENT_ID }}
         cx_client_secret: ${{ secrets.SECRET }}
	         
